Name:           perl-Crypt-RSA
Version:        1.99
Release:        1%{?dist}
Summary:        RSA public-key cryptosystem
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Crypt-RSA/
Source0:        http://www.cpan.org/authors/id/V/VI/VIPUL/Crypt-RSA-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.6.0
BuildRequires:  perl(Class::Loader) >= 2.00
BuildRequires:  perl(Convert::ASCII::Armour)
BuildRequires:  perl(Crypt::Blowfish)
BuildRequires:  perl(Crypt::CBC)
BuildRequires:  perl(Crypt::Primes) >= 0.38
BuildRequires:  perl(Crypt::Random) >= 0.34
BuildRequires:  perl(Data::Buffer)
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(Digest::MD2)
BuildRequires:  perl(Digest::MD5)
BuildRequires:  perl(Digest::SHA1)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Math::Pari) >= 2.001804
BuildRequires:  perl(Sort::Versions)
BuildRequires:  perl(Tie::EncryptedHash)
Requires:       perl(Class::Loader) >= 2.00
Requires:       perl(Convert::ASCII::Armour)
Requires:       perl(Crypt::Blowfish)
Requires:       perl(Crypt::CBC)
Requires:       perl(Crypt::Primes) >= 0.38
Requires:       perl(Crypt::Random) >= 0.34
Requires:       perl(Data::Buffer)
Requires:       perl(Data::Dumper)
Requires:       perl(Digest::MD2)
Requires:       perl(Digest::MD5)
Requires:       perl(Digest::SHA1)
Requires:       perl(Math::Pari) >= 2.001804
Requires:       perl(Sort::Versions)
Requires:       perl(Tie::EncryptedHash)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Crypt::RSA is a pure-perl, cleanroom implementation of the RSA public-key
cryptosystem. It uses Math::Pari(3), a perl interface to the blazingly fast
PARI library, for big integer arithmetic and number theoretic computations.

%prep
%setup -q -n Crypt-RSA-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ARTISTIC Changes COPYING MANIFEST.skip README TODO
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Mar 19 2019 Johannes Grumboeck <johannes.grumboeck@porscheinformatik.at> 1.99-1
- Specfile autogenerated by cpanspec 1.78.
